# #####################################################################
# Automatically generated by qmake (2.01a) Tue Nov 3 14:24:31 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fretboard.h \
    chord.h \
    note.h \
    mainwindow.h
SOURCES += fretboard.cpp \
    main.cpp \
    chord.cpp \
    note.cpp \
    mainwindow.cpp
FORMS += 
